import { registerEnumType } from '@nestjs/graphql';

export enum UserStatus {
  DISABLED = 'DISABLED',
  REGISTERED = 'REGISTERED',
  OAUTHREGISTERED = 'OAUTHREGISTERED',
  REGISTERED_BY_ORDER = 'REGISTERED_BY_ORDER',
  REGISTERED_BY_SUPPORTING = 'REGISTERED_BY_SUPPORTING',
  REGISTERED_AND_CONFIRMED = 'REGISTERED_AND_CONFIRMED',
  REGISTERED_SUPPORTER = 'REGISTERED_SUPPORTER',
}

registerEnumType(UserStatus, {
  name: 'UserStatus',
});
